version: '3.4'

services:   
  mongodb:
    image: mongo
    networks:
      - my-network-name
    ports:
      - "27018:27017"
      
  services: 
    build:
      context: .
      dockerfile: BookApi/Dockerfile           
    ports:
      - "5000:80"                
    networks:
      - my-network-name
           
networks:
  my-network-name:
    driver: bridge  
